packages:
    - apps/*
    - packages/*

catalog:
    "@tanstack/react-query": ^5.90.12
    eslint: ^9.39.1
    prettier: ^3.7.4
    react: ^19.2.3
    react-dom: ^19.2.3
    typescript: ^5.9.3
    viem: ^2.55.13
    wagmi: ^2.18.2

strictDepBuilds: true
blockExoticSubdeps: true
minimumReleaseAge: 10080
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200

allowBuilds:
    "@parcel/watcher": true
    "@vercel/speed-insights": true
    bufferutil: true
    core-js-pure: true
    esbuild: true
    keccak: true
    msw: false
    protobufjs: true
    secp256k1: true
    sharp: true
    utf-8-validate: true
