packages:
    - apps/*
    - packages/*

catalog:
    eslint: ^9.39.1
    prettier: ^3.7.4
    typescript: ^5.9.3
    viem: ^2.41.2
    wagmi: ^2.18.2
    "@tanstack/react-query": ^5.90.12
    react: "^19.2.3"
    "react-dom": "^19.2.3"

onlyBuiltDependencies:
    - "@parcel/watcher"
    - "@vercel/speed-insights"
    - bufferutil
    - esbuild
    - keccak
    - protobufjs
    - secp256k1
    - sharp
    - utf-8-validate
