packages:
  - apps/*
  - packages/*

shamefullyHoist: true
onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - bufferutil
  - esbuild
  - keccak
  - protobufjs
  - secp256k1
  - sharp
  - utf-8-validate
