blank_issues_enabled: false
contact_links:
    - name: 🤔 Questions and Help
      url: https://discord.gg/cartesi
      about: This issue tracker is not for support questions. Please refer to the discord Cartesi Development Community server for help and discussion.
