export type ConnectionNetworkStatus =
    | "idle"
    | "pending"
    | "error"
    | "success"
    | "noop";

type ConfigType = "system" | "system_mock" | "user";

export interface NodeConnectionConfig {
    // saved instances has an ID generated by the database.
    id?: number;
    name: string;
    url: string;
    chain?: {
        id: number;
        rpcUrl: string;
    };
    version: string;
    timestamp: number;
    isPreferred: boolean;
    isDeletable: boolean;
    type: ConfigType;
}

export type DbNodeConnectionConfig = Required<NodeConnectionConfig>;

export interface Repository {
    add: (conn: NodeConnectionConfig) => Promise<DbNodeConnectionConfig>;
    remove: (id: number) => Promise<boolean>;
    get: (id: number) => Promise<DbNodeConnectionConfig | null>;
    list: () => Promise<DbNodeConnectionConfig[]>;
}
