import { AutoloadResult } from "@shazow/whatsabi";
import { Hex } from "viem";
import { baseSepolia } from "viem/chains";

type ABI = AutoloadResult["abi"];

const chainId = baseSepolia.id;
const payload: Hex =
    "0xa9059cbb0000000000000000000000000769e15f8d7042969aeb78e73b54192b3c4ec8bc000000000000000000000000000000000000000000000000000000000007a120";
const destination: Hex = "0x036cbd53842c5426634e7929541ec2318f3dcf7e";
const destination2: Hex = "0xec6adef5e1006bb305bb1975333e8fc4071295bf";
const payload2: Hex =
    "0xa9059cbb000000000000000000000000d91c0c2fc065a2e094129066d2683ef16e6f60320000000000000000000000000000000000000000000000d8d726b7177a800000";

const withdrawV2EtherDestination: Hex =
    "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266";

const payloadWithdrawEtherV2: Hex =
    "0x237a816f000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb922660000000000000000000000000000000000000000000000001bc16d674ec8000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000";

const voucherOutputV2Destination: Hex =
    "0x9A676e781A523b5d0C0e43731313A708CB607508";
const payloadVoucherOutputV2: Hex =
    "0x237a816f0000000000000000000000009a676e781a523b5d0c0e43731313a708cb60750800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000004440c10f190000000000000000000000009965507d1a55bcc2695c58ba16fb37d819b0a4dc000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

const validABIByDestination: Record<Hex, ABI> = {
    [destination2]: [
        {
            name: "balanceOf",
            type: "function",
            stateMutability: "nonpayable",
            inputs: [
                {
                    type: "address",
                    name: "user",
                },
            ],
            outputs: [],
            selector: "",
        },
    ],
    [destination]: [
        {
            type: "function",
            selector: "0xef55bec6",
            sig: "receiveWithAuthorization(address,address,uint256,uint256,uint256,bytes32,uint8,bytes32,bytes32)",
            name: "receiveWithAuthorization",
            payable: false,
            inputs: [
                { type: "address", name: "" },
                { type: "address", name: "" },
                { type: "uint256", name: "" },
                { type: "uint256", name: "" },
                { type: "uint256", name: "" },
                { type: "bytes32", name: "" },
                { type: "uint8", name: "" },
                { type: "bytes32", name: "" },
                { type: "bytes32", name: "" },
            ],
        },
        {
            type: "function",
            selector: "0xf2fde38b",
            sig: "transferOwnership(address)",
            name: "transferOwnership",
            payable: false,
            inputs: [{ type: "address", name: "" }],
        },
        {
            type: "function",
            selector: "0xf9f92be4",
            sig: "blacklist(address)",
            name: "blacklist",
            payable: false,
            inputs: [{ type: "address", name: "" }],
        },
        {
            type: "function",
            selector: "0xfe575a87",
            sig: "isBlacklisted(address)",
            name: "isBlacklisted",
            payable: false,
            inputs: [{ type: "address", name: "" }],
        },
        {
            type: "function",
            selector: "0xe3ee160e",
            sig: "transferWithAuthorization(address,address,uint256,uint256,uint256,bytes32,uint8,bytes32,bytes32)",
            name: "transferWithAuthorization",
            payable: false,
            inputs: [
                { type: "address", name: "" },
                { type: "address", name: "" },
                { type: "uint256", name: "" },
                { type: "uint256", name: "" },
                { type: "uint256", name: "" },
                { type: "bytes32", name: "" },
                { type: "uint8", name: "" },
                { type: "bytes32", name: "" },
                { type: "bytes32", name: "" },
            ],
        },
        {
            type: "function",
            selector: "0xe5a6b10f",
            sig: "currency()",
            name: "currency",
            payable: false,
            inputs: [],
        },
        {
            type: "function",
            selector: "0xe94a0102",
            sig: "authorizationState(address,bytes32)",
            name: "authorizationState",
            payable: false,
            inputs: [
                { type: "address", name: "" },
                { type: "bytes32", name: "" },
            ],
        },
        {
            type: "function",
            selector: "0xd505accf",
            sig: "permit(address,address,uint256,uint256,uint8,bytes32,bytes32)",
            name: "permit",
            payable: false,
            inputs: [
                { type: "address", name: "" },
                { type: "address", name: "" },
                { type: "uint256", name: "" },
                { type: "uint256", name: "" },
                { type: "uint8", name: "" },
                { type: "bytes32", name: "" },
                { type: "bytes32", name: "" },
            ],
            sigAlts: [
                "$____$$_$$___$$$_$$$$__$$$__$$$$$$$$$(address,address,uint256,uint256,uint8,bytes32,bytes32)",
            ],
        },
        {
            type: "function",
            selector: "0xd608ea64",
            sig: "initializeV2(string)",
            name: "initializeV2",
            payable: false,
            inputs: [{ type: "string", name: "" }],
        },
        {
            type: "function",
            selector: "0xd9169487",
            sig: "CANCEL_AUTHORIZATION_TYPEHASH()",
            name: "CANCEL_AUTHORIZATION_TYPEHASH",
            payable: false,
            inputs: [],
        },
        {
            type: "function",
            selector: "0xdd62ed3e",
            sig: "allowance(address,address)",
            name: "allowance",
            payable: false,
            inputs: [
                { type: "address", name: "" },
                { type: "address", name: "" },
            ],
        },
        {
            type: "function",
            selector: "0xb7b72899",
            sig: "cancelAuthorization(address,bytes32,bytes)",
            name: "cancelAuthorization",
            payable: false,
            inputs: [
                { type: "address", name: "" },
                { type: "bytes32", name: "" },
                { type: "bytes", name: "" },
            ],
        },
        {
            type: "function",
            selector: "0xbd102430",
            sig: "blacklister()",
            name: "blacklister",
            payable: false,
            inputs: [],
        },
        {
            type: "function",
            selector: "0xcf092995",
            sig: "transferWithAuthorization(address,address,uint256,uint256,uint256,bytes32,bytes)",
            name: "transferWithAuthorization",
            payable: false,
            inputs: [
                { type: "address", name: "" },
                { type: "address", name: "" },
                { type: "uint256", name: "" },
                { type: "uint256", name: "" },
                { type: "uint256", name: "" },
                { type: "bytes32", name: "" },
                { type: "bytes", name: "" },
            ],
        },
        {
            type: "function",
            selector: "0xaa20e1e4",
            sig: "updateMasterMinter(address)",
            name: "updateMasterMinter",
            payable: false,
            inputs: [{ type: "address", name: "" }],
        },
        {
            type: "function",
            selector: "0xaa271e1a",
            sig: "isMinter(address)",
            name: "isMinter",
            payable: false,
            inputs: [{ type: "address", name: "" }],
        },
        {
            type: "function",
            selector: "0xad38bf22",
            sig: "updateBlacklister(address)",
            name: "updateBlacklister",
            payable: false,
            inputs: [{ type: "address", name: "" }],
        },
        {
            type: "function",
            selector: "0xb2118a8d",
            sig: "rescueERC20(address,address,uint256)",
            name: "rescueERC20",
            payable: false,
            inputs: [
                { type: "address", name: "" },
                { type: "address", name: "" },
                { type: "uint256", name: "" },
            ],
        },
        {
            type: "function",
            selector: "0xa0cc6a68",
            sig: "TRANSFER_WITH_AUTHORIZATION_TYPEHASH()",
            name: "TRANSFER_WITH_AUTHORIZATION_TYPEHASH",
            payable: false,
            inputs: [],
        },
        {
            type: "function",
            selector: "0xa457c2d7",
            sig: "decreaseAllowance(address,uint256)",
            name: "decreaseAllowance",
            payable: false,
            inputs: [
                { type: "address", name: "" },
                { type: "uint256", name: "" },
            ],
        },
        {
            type: "function",
            selector: "0xa9059cbb",
            sig: "transfer(address,uint256)",
            name: "transfer",
            payable: false,
            inputs: [
                { type: "address", name: "" },
                { type: "uint256", name: "" },
            ],
        },
        {
            type: "function",
            selector: "0x8da5cb5b",
            sig: "owner()",
            name: "owner",
            payable: false,
            inputs: [],
        },
        {
            type: "function",
            selector: "0x95d89b41",
            sig: "symbol()",
            name: "symbol",
            payable: false,
            inputs: [],
        },
        {
            type: "function",
            selector: "0x9fd0506d",
            sig: "pauser()",
            name: "pauser",
            payable: false,
            inputs: [],
        },
        {
            type: "function",
            selector: "0x9fd5a6cf",
            sig: "permit(address,address,uint256,uint256,bytes)",
            name: "permit",
            payable: false,
            inputs: [
                { type: "address", name: "" },
                { type: "address", name: "" },
                { type: "uint256", name: "" },
                { type: "uint256", name: "" },
                { type: "bytes", name: "" },
            ],
        },
        {
            type: "function",
            selector: "0x8456cb59",
            sig: "pause()",
            name: "pause",
            payable: false,
            inputs: [],
        },
        {
            type: "function",
            selector: "0x88b7ab63",
            sig: "receiveWithAuthorization(address,address,uint256,uint256,uint256,bytes32,bytes)",
            name: "receiveWithAuthorization",
            payable: false,
            inputs: [
                { type: "address", name: "" },
                { type: "address", name: "" },
                { type: "uint256", name: "" },
                { type: "uint256", name: "" },
                { type: "uint256", name: "" },
                { type: "bytes32", name: "" },
                { type: "bytes", name: "" },
            ],
        },
        {
            type: "function",
            selector: "0x8a6db9c3",
            sig: "minterAllowance(address)",
            name: "minterAllowance",
            payable: false,
            inputs: [{ type: "address", name: "" }],
        },
        {
            type: "function",
            selector: "0x5c975abb",
            sig: "paused()",
            name: "paused",
            payable: false,
            inputs: [],
        },
        {
            type: "function",
            selector: "0x70a08231",
            sig: "balanceOf(address)",
            name: "balanceOf",
            payable: false,
            inputs: [{ type: "address", name: "" }],
        },
        {
            type: "function",
            selector: "0x7ecebe00",
            sig: "nonces(address)",
            name: "nonces",
            payable: false,
            inputs: [{ type: "address", name: "" }],
            sigAlts: ["_$_$$_$__$$$$$$$$__$__$$_$$$_$$$(address)"],
        },
        {
            type: "function",
            selector: "0x7f2eecc3",
            sig: "RECEIVE_WITH_AUTHORIZATION_TYPEHASH()",
            name: "RECEIVE_WITH_AUTHORIZATION_TYPEHASH",
            payable: false,
            inputs: [],
        },
        {
            type: "function",
            selector: "0x54fd4d50",
            sig: "version()",
            name: "version",
            payable: false,
            inputs: [],
        },
        {
            type: "function",
            selector: "0x554bab3c",
            sig: "updatePauser(address)",
            name: "updatePauser",
            payable: false,
            inputs: [{ type: "address", name: "" }],
        },
        {
            type: "function",
            selector: "0x5a049a70",
            sig: "cancelAuthorization(address,bytes32,uint8,bytes32,bytes32)",
            name: "cancelAuthorization",
            payable: false,
            inputs: [
                { type: "address", name: "" },
                { type: "bytes32", name: "" },
                { type: "uint8", name: "" },
                { type: "bytes32", name: "" },
                { type: "bytes32", name: "" },
            ],
        },
        {
            type: "function",
            selector: "0x40c10f19",
            sig: "mint(address,uint256)",
            name: "mint",
            payable: false,
            inputs: [
                { type: "address", name: "" },
                { type: "uint256", name: "" },
            ],
        },
        {
            type: "function",
            selector: "0x42966c68",
            sig: "burn(uint256)",
            name: "burn",
            payable: false,
            inputs: [{ type: "uint256", name: "" }],
        },
        {
            type: "function",
            selector: "0x430239b4",
            sig: "initializeV2_2(address[],string)",
            name: "initializeV2_2",
            payable: false,
            inputs: [
                { type: "address[]", name: "" },
                { type: "string", name: "" },
            ],
        },
        {
            type: "function",
            selector: "0x4e44d956",
            sig: "configureMinter(address,uint256)",
            name: "configureMinter",
            payable: false,
            inputs: [
                { type: "address", name: "" },
                { type: "uint256", name: "" },
            ],
        },
        {
            type: "function",
            selector: "0x38a63183",
            sig: "rescuer()",
            name: "rescuer",
            payable: false,
            inputs: [],
        },
        {
            type: "function",
            selector: "0x39509351",
            sig: "increaseAllowance(address,uint256)",
            name: "increaseAllowance",
            payable: false,
            inputs: [
                { type: "address", name: "" },
                { type: "uint256", name: "" },
            ],
        },
        {
            type: "function",
            selector: "0x3f4ba83a",
            sig: "unpause()",
            name: "unpause",
            payable: false,
            inputs: [],
        },
        {
            type: "function",
            selector: "0x313ce567",
            sig: "decimals()",
            name: "decimals",
            payable: false,
            inputs: [],
        },
        {
            type: "function",
            selector: "0x3357162b",
            sig: "initialize(string,string,string,uint8,address,address,address,address)",
            name: "initialize",
            payable: false,
            inputs: [
                { type: "string", name: "" },
                { type: "string", name: "" },
                { type: "string", name: "" },
                { type: "uint8", name: "" },
                { type: "address", name: "" },
                { type: "address", name: "" },
                { type: "address", name: "" },
                { type: "address", name: "" },
            ],
        },
        {
            type: "function",
            selector: "0x35d99f35",
            sig: "masterMinter()",
            name: "masterMinter",
            payable: false,
            inputs: [],
        },
        {
            type: "function",
            selector: "0x3644e515",
            sig: "DOMAIN_SEPARATOR()",
            name: "DOMAIN_SEPARATOR",
            payable: false,
            inputs: [],
        },
        {
            type: "function",
            selector: "0x2fc81e09",
            sig: "initializeV2_1(address)",
            name: "initializeV2_1",
            payable: false,
            inputs: [{ type: "address", name: "" }],
        },
        {
            type: "function",
            selector: "0x3092afd5",
            sig: "removeMinter(address)",
            name: "removeMinter",
            payable: false,
            inputs: [{ type: "address", name: "" }],
        },
        {
            type: "function",
            selector: "0x30adf81f",
            sig: "PERMIT_TYPEHASH()",
            name: "PERMIT_TYPEHASH",
            payable: false,
            inputs: [],
        },
        {
            type: "function",
            selector: "0x1a895266",
            sig: "unBlacklist(address)",
            name: "unBlacklist",
            payable: false,
            inputs: [{ type: "address", name: "" }],
        },
        {
            type: "function",
            selector: "0x23b872dd",
            sig: "transferFrom(address,address,uint256)",
            name: "transferFrom",
            payable: false,
            inputs: [
                { type: "address", name: "" },
                { type: "address", name: "" },
                { type: "uint256", name: "" },
            ],
        },
        {
            type: "function",
            selector: "0x2ab60045",
            sig: "updateRescuer(address)",
            name: "updateRescuer",
            payable: false,
            inputs: [{ type: "address", name: "" }],
        },
        {
            type: "function",
            selector: "0x06fdde03",
            sig: "name()",
            name: "name",
            payable: false,
            inputs: [],
        },
        {
            type: "function",
            selector: "0x095ea7b3",
            sig: "approve(address,uint256)",
            name: "approve",
            payable: false,
            inputs: [
                { type: "address", name: "" },
                { type: "uint256", name: "" },
            ],
        },
        {
            type: "function",
            selector: "0x18160ddd",
            sig: "totalSupply()",
            name: "totalSupply",
            payable: false,
            inputs: [],
        },
    ],
    [voucherOutputV2Destination]: [
        {
            type: "function",
            selector: "0xa22cb465",
            sig: "setApprovalForAll(address,bool)",
            name: "setApprovalForAll",
            payable: false,
            inputs: [
                {
                    type: "address",
                    name: "",
                },
                {
                    type: "bool",
                    name: "",
                },
            ],
        },
        {
            type: "function",
            selector: "0xe985e9c5",
            sig: "isApprovedForAll(address,address)",
            name: "isApprovedForAll",
            payable: false,
            inputs: [
                {
                    type: "address",
                    name: "",
                },
                {
                    type: "address",
                    name: "",
                },
            ],
        },
        {
            type: "function",
            selector: "0xf242432a",
            sig: "safeTransferFrom(address,address,uint256,uint256,bytes)",
            name: "safeTransferFrom",
            payable: false,
            inputs: [
                {
                    type: "address",
                    name: "",
                },
                {
                    type: "address",
                    name: "",
                },
                {
                    type: "uint256",
                    name: "",
                },
                {
                    type: "uint256",
                    name: "",
                },
                {
                    type: "bytes",
                    name: "",
                },
            ],
        },
        {
            type: "function",
            selector: "0xf2fde38b",
            sig: "transferOwnership(address)",
            name: "transferOwnership",
            payable: false,
            inputs: [
                {
                    type: "address",
                    name: "",
                },
            ],
        },
        {
            type: "function",
            selector: "0x4e1273f4",
            sig: "balanceOfBatch(address[],uint256[])",
            name: "balanceOfBatch",
            payable: false,
            inputs: [
                {
                    type: "address[]",
                    name: "",
                },
                {
                    type: "uint256[]",
                    name: "",
                },
            ],
        },
        {
            type: "function",
            selector: "0x715018a6",
            sig: "renounceOwnership()",
            name: "renounceOwnership",
            payable: false,
            inputs: [],
        },
        {
            type: "function",
            selector: "0x8da5cb5b",
            sig: "owner()",
            name: "owner",

            payable: false,
            inputs: [],
        },
        {
            type: "function",
            selector: "0x0e89341c",
            sig: "uri(uint256)",
            name: "uri",
            payable: false,
            inputs: [
                {
                    type: "uint256",
                    name: "",
                },
            ],
        },
        {
            type: "function",
            selector: "0x1f7fdffa",
            sig: "mintBatch(address,uint256[],uint256[],bytes)",
            name: "mintBatch",
            payable: false,
            inputs: [
                {
                    type: "address",
                    name: "",
                },
                {
                    type: "uint256[]",
                    name: "",
                },
                {
                    type: "uint256[]",
                    name: "",
                },
                {
                    type: "bytes",
                    name: "",
                },
            ],
        },
        {
            type: "function",
            selector: "0x2eb2c2d6",
            sig: "safeBatchTransferFrom(address,address,uint256[],uint256[],bytes)",
            name: "safeBatchTransferFrom",
            payable: false,
            inputs: [
                {
                    type: "address",
                    name: "",
                },
                {
                    type: "address",
                    name: "",
                },
                {
                    type: "uint256[]",
                    name: "",
                },
                {
                    type: "uint256[]",
                    name: "",
                },
                {
                    type: "bytes",
                    name: "",
                },
            ],
        },
        {
            type: "function",
            selector: "0x40c10f19",
            sig: "mint(address,uint256)",
            name: "mint",
            payable: false,
            inputs: [
                {
                    type: "address",
                    name: "",
                },
                {
                    type: "uint256",
                    name: "",
                },
            ],
        },
        {
            type: "function",
            selector: "0x00fdd58e",
            sig: "balanceOf(address,uint256)",
            name: "balanceOf",
            payable: false,
            inputs: [
                {
                    type: "address",
                    name: "",
                },
                {
                    type: "uint256",
                    name: "",
                },
            ],
        },
        {
            type: "function",
            selector: "0x01ffc9a7",
            sig: "supportsInterface(bytes4)",
            name: "supportsInterface",
            payable: false,
            inputs: [
                {
                    type: "bytes4",
                    name: "",
                },
            ],
        },
        {
            type: "function",
            selector: "0x02fe5305",
            sig: "setURI(string)",
            name: "setURI",
            payable: false,
            inputs: [
                {
                    type: "string",
                    name: "",
                },
            ],
        },
    ],
};

export const voucherDecoderStubs = {
    chainId,
    destination,
    destination2,
    withdrawV2EtherDestination,
    voucherOutputV2Destination,
    payload2,
    payload,
    payloadWithdrawEtherV2,
    payloadVoucherOutputV2,

    validABIByDestination,
};
