name: "Chromatic"
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  NEXT_PUBLIC_CARTESI_NODE_RPC_URL: http://127.0.0.1:10011/rpc
  NEXT_PUBLIC_MOCK_ENABLED: true
jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          fetch-depth: 0 #required to retrieve git history

      - name: Install pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 #v6.1.0
        with:
          package_json_file: "package.json"

      - name: Setup Node.js environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 #v7.0.0
        with:
          node-version: 24.19.0
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Code format check
        run: pnpm format:check

      - name: Linting
        run: pnpm lint

      - name: Build Storybook
        run: pnpm build:storybook --filter=explorer

      - name: Publish to Chromatic
        uses: chromaui/action@bb3b582719a93c1828c5e520e62992b2937d7889 #18.9.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: storybook-static
          workingDir: ./apps/explorer
          exitOnceUploaded: true
