name: Docker
on:
    push:
        tags:
            - "v*"
    pull_request:
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
permissions:
    contents: read
    packages: write
    id-token: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

            - name: Docker meta
              id: docker_meta
              uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf #v6.0.0
              with:
                  images: |
                      name=ghcr.io/cartesi/rollups-explorer
                      name=docker.io/cartesi/rollups-explorer,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
                  tags: |
                      type=semver,pattern={{version}}
                      type=ref,event=branch
                      type=ref,event=pr

            - name: Login to Docker Hub
              uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 #v4.1.0
              if: ${{ startsWith(github.ref, 'refs/tags/v') }}
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 #v4.1.0
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - uses: depot/setup-action@15c09a5f77a0840ad4bce955686522a257853461 #v1.7.1

            - name: Build and push docker image
              id: docker_build
              uses: depot/bake-action@1d58c2668346981089b088b7ef36755b206b20e9 #v1.13.0
              with:
                  files: |
                      ./docker-bake.hcl
                      ${{ steps.docker_meta.outputs.bake-file }}
                      ./docker-bake.platforms.hcl
                  push: true
                  project: ${{ vars.DEPOT_PROJECT }}
