name: Run e2e tests
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  NEXT_PUBLIC_EXPLORER_API_URL: http://localhost:4350/graphql
jobs:
  get-sepolia-deployment-url:
    runs-on: ubuntu-latest
    outputs:
      deployment-url: ${{ steps.get-deployment-url.outputs.DEPLOYMENT_URL }}
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@739bfe42ca9233c5e6aca07c1a25a9d34aca49b0 #v6.0.7
        with:
          package_json_file: "package.json"
      - name: Setup Node.js environment
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e #v6.4.0
        with:
          node-version: 22.12.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Get Sepolia deployment url
        id: get-deployment-url
        run: |
          deployment_url=$(node getSepoliaDeploymentUrl.mjs)
          echo "DEPLOYMENT_URL=$deployment_url" >> $GITHUB_OUTPUT
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}

  wait-for-sepolia-deployment:
    needs: [get-sepolia-deployment-url]
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_URL: ${{ needs.get-sepolia-deployment-url.outputs.deployment-url }}
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: UnlyEd/github-action-await-vercel@v1
        id: await-vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          deployment-url: ${{ env.DEPLOYMENT_URL }}
          timeout: 1200 # Wait for 1200 seconds (20 minutes) before failing

  run-e2e-tests-on-sepolia:
    needs: [get-sepolia-deployment-url, wait-for-sepolia-deployment]
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_URL: ${{ needs.get-sepolia-deployment-url.outputs.deployment-url }}
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-jammy
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@739bfe42ca9233c5e6aca07c1a25a9d34aca49b0 #v6.0.7

      - run: pnpm --version

      - name: Setup Node.js environment
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e #v6.4.0
        with:
          node-version: 22.12.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright
        env:
          PLAYWRIGHT_BROWSERS_PATH: /root/.cache/ms-playwright
        run: cd apps/web && pnpm exec playwright install --with-deps
      - name: Run e2e tests
        run: pnpm test:e2e
        id: e2e
        env:
          E2E_BASE_URL: ${{ env.DEPLOYMENT_URL }}
          HOME: /root
