name: Test action
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  NEXT_PUBLIC_EXPLORER_API_URL: http://localhost:4350/graphql
jobs:
  get-sepolia-deployment-url:
    runs-on: ubuntu-latest
    outputs:
      deployment-url: ${{ steps.get-deployment-url.outputs.DEPLOYMENT_URL }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0
          cache: "yarn"

      - name: Get Sepolia deployment url
        id: get-deployment-url
        run: |
          deployment_url=$(node getSepoliaDeploymentUrl.mjs ${{ secrets.VERCEL_TOKEN }})
          echo "DEPLOYMENT_URL=$deployment_url" >> $GITHUB_OUTPUT

  wait-for-vercel-deployment:
    needs: [get-sepolia-deployment-url]
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_URL: ${{ needs.get-sepolia-deployment-url.outputs.deployment-url }}
    steps:
      - name: Get Sepolia deployment url
        run: |
          echo "DEPLOYMENT_URL is: " $DEPLOYMENT_URL