name: Test action
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  NEXT_PUBLIC_EXPLORER_API_URL: http://localhost:4350/graphql
jobs:
  get-sepolia-deployment-url:
    runs-on: ubuntu-latest
    outputs:
      pr-number: ${{ steps.check-prs.outputs.PR_NUMBER }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0
          cache: "yarn"

      - name: Get Sepolia deployment url
        id: check-prs
        run: |
          ROLLUPS_EXPLORER_SEPOLIA_URL=$(node getSepoliaDeploymentUrl.mjs ${{ secrets.VERCEL_TOKEN }})
          echo "Rollups Explorer Sepolia Urll: " $ROLLUPS_EXPLORER_SEPOLIA_URL
          echo "PR_NUMBER=$pr_number" >> $GITHUB_OUTPUT

  wait-for-vercel-deployment:
    needs: [get-sepolia-deployment-url]
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ needs.get-sepolia-deployment-url.outputs.pr-number }}
    steps:
      - name: Get Sepolia deployment url
        id: get-sepolia-deployment-url
        run: |
          echo "PR_NUMBER is: " $PR_NUMBER