name: Test action
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  NEXT_PUBLIC_EXPLORER_API_URL: http://localhost:4350/graphql
jobs:
  get-info:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 22.11.0
          cache: "yarn"

      - name: Test secrets
        run: |
          # Get the team id
          TEAM_ID=$(node getSepoliaDeploymentUrl.mjs ${{ secrets.VERCEL_TOKEN }})
          echo "Cartesi team id: " $TEAM_ID
