name: Test action
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  NEXT_PUBLIC_EXPLORER_API_URL: http://localhost:4350/graphql
jobs:
  get-sepolia-deployment-url:
    runs-on: ubuntu-latest
    outputs:
      deployment-url: ${{ steps.get-deployment-url.outputs.DEPLOYMENT_URL }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0
          cache: "yarn"

      - name: Get Sepolia deployment url
        id: get-deployment-url
        run: |
          deployment_url=$(node getSepoliaDeploymentUrl.mjs ${{ secrets.VERCEL_TOKEN }})
          echo "DEPLOYMENT_URL=$deployment_url" >> $GITHUB_OUTPUT

  wait-for-vercel-deployment:
    needs: [get-sepolia-deployment-url]
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_URL: ${{ needs.get-sepolia-deployment-url.outputs.deployment-url }}
    steps:
      - name: Get Sepolia deployment url
        run: |
          echo "DEPLOYMENT_URL is: " $DEPLOYMENT_URL

      - uses: UnlyEd/github-action-await-vercel@v1
        id: await-vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          deployment-url: ${{ env.DEPLOYMENT_URL }}

  e2e:
    needs: [ get-sepolia-deployment-url, wait-for-vercel-deployment ]
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_URL: ${{ needs.get-sepolia-deployment-url.outputs.deployment-url }}
    container:
      image: mcr.microsoft.com/playwright:v1.53.2-jammy
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Playwright
        run: yarn playwright install --with-deps

      - name: Run e2e tests
        run: yarn test:e2e
        id: e2e
        continue-on-error: true
        env:
          E2E_BASE_URL: ${{ env.DEPLOYMENT_URL }}
          HOME: /root