name: Test action
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  NEXT_PUBLIC_EXPLORER_API_URL: http://localhost:4350/graphql
jobs:
  get-info:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0
          cache: "yarn"

      - name: Test secrets
        run: |
          # Get the team ids
          TEAMS=`curl -H 'Accept: application/json' -H 'Content-Type: application/json' -H 'Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}' https://api.vercel.com/v2/teams`
          
          # Get the Cartesi team id
          CARTESI_TEAM_ID=`node -pe 'JSON.parse(process.argv[1]).teams.find((team) => team.slug === "cartesi").id' $TEAMS`
          echo "Vercel deployments for current team: " $TEAMS
          
          # Fetch all current Vercel deployments for the Cartesi team
          VERCEL_DEPLOYMENTS=`curl "https://api.vercel.com/v6/deployments?teamId=$TEAM_ID" -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}"`
          echo "Vercel deployments for current team: " VERCEL_DEPLOYMENTS
